### PR TITLE
Creat api documentation

### PR DESCRIPTION
**Pull request by lienharc**
Updated the api documentation.

### CODE REVIEW

**Comment by lienharc** [comment]
For a compiled version of the readme, see here: https://github.com/netzbegruenung/candymat/tree/creat-api-documentation/backend

**Review by Pit-Storm — COMMENTED** [review]
Great work. Let's do it like that.

There are some spellings, but this is less relevant.

I dropped the idea to create this backend via graphql, because the data we recieve from the api is very small and there are not many clients expected per instance. If this is coming up to horizon, we can think again about rebuilding the api with graphql. But for now its great :-)

**Comment by lienharc** [comment]
Actually lets talk about the graphql idea. 

This is whole project is a hobby project and I really had fun writing this documentation and thinking about RESTful APIs. I don't mind never actually implementing it (because probably a little bit less fun). 
Getting to know graphQL sounds great and if you think the same or even have already some experience I'm happy to do this with graphql from the beginning.

**Comment by Pit-Storm** [comment]
I am starting to work with graphql at workplace. The concept and available implementations are realy straight forward.

It is just about setting up a database, starting a graphql server and after connecting them the server auto discovers the database schema, what types of operations on each table is allowed.

Postgraphile is an implementation for postgreSQL as a backend for a  graphql.server.

Maybe we should catch up at a voice chat next week to decide this and/or even starting this thing up.

**Comment by lienharc** [comment]
Decision to go for graphQL.

For documentation reasons this README is still merged although out-of-date from the beginning.

**Pull request merged**
